dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: urma-github
    token:
      secure: o7kVQSqcWqF4L7oiIr+B0i/4vIxNWv6egUd3FRvBWowCqXjPB/u5j9OmOp1sOWYLtyLum6Dmy37bEwm2sN4dWi4euwEpPcDGlCTEYtaDWiHmgBjgSQfQP2DUclaqdYLb0q19cXMScOw1w6XRZSOWye+frNNEHL+17RKMQABRk9YCi9rJZ2gOTgCMaHVLgLmt0mjFd5ox0ELYsqK0BzWrLB0aklM/mVN1x1vE0ycdTiZfwB0DhHW4kXPXF+afBBSCQ3xZg7al6zTrq6b+b8Qrg3DH27JoLh8X490ptJQoFblpKhT0UBSC6M8gl1YVYaBS8Qag94vpVEskt+YiHtJYCJJiCZj0K5M8L2sRaOsJPcZEpV7iaeMkMtTuWbiL+1gspyXbNLme5y8/998B8Fl4VagNL64GUHAIqkK83H4L7jb7JNIXbe6iZhFZep0lgBTXjFD2jvv0IxTZEtgBK4vv2ZVIrSQLXYvH/cdWPSx1hKVbA6Mmcxt0Bq2ZL7/XMHnhzuz9GVhdBHVCINXDiOB+Yujqvs/G6e/pCPUOpUoYS5JDmhvvLGRs/qbvv4K24oXEpVZ2xi9A6ZVfLw6EYATmMvLUseMLIhpVE1QSQN/Uf/VFa2LWsCqbYgpbSlp/T329Ei8ivHwRePy6SBo/2ZC+lGTUOVBZUuVO4DdwYsi6sWE=

jdk:
- oraclejdk8

script:
- sonar-scanner

cache:
  directories:
  - "$HOME/.sonar/cache"

notifications:
  slack:
    secure: tCkHYYG1LEFlbtIXPjOvW5XcOkbGNMT9FA+I91/BR0+zcm3DP1CajI/tW1DPvYKmdVr92Vwam0yd7TkCnH13RU/C5dVXkxDlNBQrKvu18RmTO8NAv0F9y6MuCDgi+abpWX3mOkZvxJH+lWoSiG/rD+MtThB0NFz7xuDynJwSDb2H1tRY1DKzPw2d/IovNdlQyn7xxNz+oWSMPiYQTpVgZhUu6oDf9lA/W4vHh37HzeJtxbyXoUZFQLlqkG3uGqmfjO/Vmh6qk7/46mh55AH5p5M4lO1KIqj26dJyCfWBpkeoToiyWKCKZvig27f22yZBIEBllOy4W7eWhFspVGcitBhnrtGdsmecFQZeyXmNkLdeiL3ZMBH+97zY/3cdy5uBpobp1EnrZw1X29voHxeLIBM9GsNEeJ8H6AupMd4XggATSOqOwbz7QwcfQdI60gOgChaUmiwQ9Fq04FVvqUje1EvA6A/APbj789CZd8n/5Dyekz9s4z0jsD2jgoMUDttFUXsAbypfSK38ZKU2tIknpR9bGMgVFTWqnB6xrF+iUC2i6OycYCijbOO7lfgWACqoc/dxMRZku8dDNTG6WLtUrM038+RqjjsGMz5p0bxDLu47rTQKYSWFYn/e/p7U2Vh9wuXm75WGUZk4Bl0K4V6t3eeLbPRSz9VlzX7HpQ/bvRk=
